GET http://localhost:3000/books/

###

GET http://localhost:3000/books/1/

###

POST http://localhost:3000/books/
Content-Type: application/json

{
  "title": "Annasalai Singamalai",
  "authorId": 13,
  "rating": 5,
  "ratingCount": 5126559,
  "reviewCount": 6151,
  "description": "dfdfdf There is a door at the end of a silent corridor.",
  "pages": 352,
  "dateOfPublication": "May 1st 2003",
  "editionLanguage": "Englishdfdfd",
  "price": 850,
  "onlineStores": "fdfdfd,Amazon,Audible,Indigo,Apple Books,Google Play,IndieBound"
}

###

PUT http://localhost:3000/books/40/
Content-Type: application/json

{
  "title": "Annasalai Singamalai && Harry Potter and the Order of the Phoenix",
  "authorId": 1,
  "rating": 5,
  "ratingCount": 1000000,
  "reviewCount": 711,
  "description": "There is a door at the end of a silent corridor.",
  "pages": 352,
  "dateOfPublication": "May 1st 2003",
  "editionLanguage": "English",
  "price": 850,
  "onlineStores": "Amazon,Audible,Indigo,Apple Books,Google Play,IndieBound"
}

###

DELETE http://localhost:3000/books/42/

###

GET http://localhost:3000/authors/2/books/